### ISSUE TITLE
Duplicate symbols on linking when targeting the simulator

### ISSUE THREAD

**Issue by bscofield** [AppsFlyerSDK/AppsFlyerFramework#6]
I'm having a heck of a time getting my project to build against the simulator -- I'm getting the following errors:

```
duplicate symbol _llvm.cmdline in:
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerTracker.o)
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerUtils.o)
duplicate symbol _llvm.embedded.module in:
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerTracker.o)
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerUtils.o)
duplicate symbol _llvm.cmdline in:
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerTracker.o)
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerServerHandler.o)
duplicate symbol _llvm.embedded.module in:
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerTracker.o)
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerServerHandler.o)
duplicate symbol _llvm.cmdline in:
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerTracker.o)
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerRequestCache.o)
duplicate symbol _llvm.embedded.module in:
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerTracker.o)
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerRequestCache.o)
duplicate symbol _llvm.cmdline in:
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerTracker.o)
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerRequestCacheData.o)
duplicate symbol _llvm.embedded.module in:
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerTracker.o)
    /Users/ben/obfuscated/AppsFlyer.framework/AppsFlyer(AppsFlyerRequestCacheData.o)
ld: 8 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I copied the framework to my project, and I see these errors both when using **Link Binary with Libraries** and when adding `-framework AppsFlyer` to my **Other Linker Flags**

Any guidance would be much appreciated.

**Comment by golan19** [comment]
@bscofield:  What Xcode version are you using?

**Comment by bscofield** [comment]
@golan19 Xcode 6.4, targeting iOS 7.0 for deployment.

**Comment by golan19** [comment]
@bscofield its a known issue, please contact our support: support@appsflyer.com or send me your email, we have a framework version for Xcode 6.4.

**Comment by bscofield** [comment]
Will do, thanks!

**Comment by mmarshak** [comment]
I hit the same issue, where can I get the framework / pod that works on Xcode 6.4?
