### ISSUE TITLE
[SPM][Xcode 12.5] Unable to build for release

### ISSUE THREAD

**Issue by victorBaro** [AppsFlyerSDK/AppsFlyerFramework#171]
# Report

## SDK Version

`6.2.6`

## What did you do?

Add Appsflyer as SPM dependency

## What did you expect to happen?

Our app builds&run in debug mode but not in release configuration

## What happened instead?

App does not compile in release mode. It is possible to archive it, but when I try to build&run I get the following error:
```
missing required architecture arm64 in file /Users/victorbaro/Library/Developer/Xcode/DerivedData/Universe-hhtnbyfmvrffwmetinppdcipdpzy/Build/Products/Release-iphonesimulator/PackageFrameworks/AppsFlyerLib.framework/AppsFlyerLib (2 slices)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_AppsFlyerLib", referenced from:
      objc-class-ref in UniverseAnalytics.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Please provide any other relevant information.
It is weird that I can build&run for the simulator in debug mode but not in release mode. Also weird that it allows me to archive in release mode. I haven't tried to submit a new App Store release yet.

**Comment by mathaeus** [comment]
Hi @victorBaro, have you already tried with the latest version that was released yesterday? It seems like there are some changes that could potentially fix your error. Not really sure though
https://github.com/AppsFlyerSDK/AppsFlyerFramework/compare/6.2.6...6.3.0

I, for myself, face a similar yet different issue with code signing for release builds only, that unfortunately still persists 😞.
Are you using a `Watch` target by any chance? Because we are and the problems seems to lie there. Although we don't even link AppsFlyer to the `Watch` target...

**Comment by andr-ggn** [comment]
@victorBaro SPM works in 6.3.0
@mathaeus From your screenshot I see that XCode tries to copy our static framework into Watch bundle. This is not correct behaviour.

**Comment by andr-ggn** [comment]
@mathaeus 
Try to use this https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/157#issuecomment-810248321 
But change folder to `.../Watch/...

**Comment by mathaeus** [comment]
Thanks for the tipp @andr-ggn. 

In the meantime I was able to confirm that the issue does NOT happen with `Xcode 12.5`, so it really seems to be a bug in `12.4`. For now I'm stuck on `12.4` though, so I will try out that workaround, and get back to you, thanks!

**Comment by mathaeus** [comment]
So, since creating a `RELEASE` build in `Xcode 12.5` with `AppsFlyerLib 6.3.0` succeeds, I would suggest closing this issue :)
