### ISSUE TITLE
Error when updating library arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by BFMarks** [AppsFlyerSDK/AppsFlyerFramework#58]
This issue appeared when I updated from 4.6 to 4.8.3 

> 
> ld: 46 duplicate symbols for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Full logs below:

```

Ld /Users/bryanmarks/Library/Developer/Xcode/DerivedData/WingBoard-axmkrybtgaqwjxawruafszfdcwrq/Build/Intermediates.noindex/WingBoard.build/Debug-iphoneos/WingBoard.build/Objects-normal/arm64/WingBoard normal arm64
    cd /Users/bryanmarks/BryanApps/WingBoard/WingBoard
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Users/bryanmarks/Photos/Xcode 3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/bryanmarks/Photos/Xcode 3.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Users/bryanmarks/Photos/Xcode\ 3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Users/bryanmarks/Photos/Xcode\ 3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -L/Users/bryanmarks/Library/Developer/Xcode/DerivedData/WingBoard-axmkrybtgaqwjxawruafszfdcwrq/Build/Products/Debug-iphoneos -L/Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard -F/Users/bryanmarks/Library/Developer/Xcode/DerivedData/WingBoard-axmkrybtgaqwjxawruafszfdcwrq/Build/Products/Debug-iphoneos -F/Users/bryanmarks/Library/Developer/Xcode/DerivedData/WingBoard-axmkrybtgaqwjxawruafszfdcwrq/Build/Products/Debug-iphoneos/Alamofire -F/Users/bryanmarks/Library/Developer/Xcode/DerivedData/WingBoard-axmkrybtgaqwjxawruafszfdcwrq/Build/Products/Debug-iphoneos/Mixpanel -F/Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework -filelist /Users/bryanmarks/Library/Developer/Xcode/DerivedData/WingBoard-axmkrybtgaqwjxawruafszfdcwrq/Build/Intermediates.noindex/WingBoard.build/Debug-iphoneos/WingBoard.build/Objects-normal/arm64/WingBoard.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/bryanmarks/Library/Developer/Xcode/DerivedData/WingBoard-axmkrybtgaqwjxawruafszfdcwrq/Build/Intermediates.noindex/WingBoard.build/Debug-iphoneos/WingBoard.build/Objects-normal/arm64/WingBoard_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-link-runtime -L/Users/bryanmarks/Photos/Xcode\ 3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/bryanmarks/Library/Developer/Xcode/DerivedData/WingBoard-axmkrybtgaqwjxawruafszfdcwrq/Build/Intermediates.noindex/WingBoard.build/Debug-iphoneos/WingBoard.build/Objects-normal/arm64/WingBoard.swiftmodule -ObjC -framework AdSupport -framework Alamofire -framework AppsFlyerLib -framework Mixpanel -framework Security -framework SystemConfiguration -framework iAd -weak_framework AdSupport -framework iAd -lAppsFlyerLib -framework Pods_WingBoard -framework StoreKit -Xlinker -dependency_info -Xlinker /Users/bryanmarks/Library/Developer/Xcode/DerivedData/WingBoard-axmkrybtgaqwjxawruafszfdcwrq/Build/Intermediates.noindex/WingBoard.build/Debug-iphoneos/WingBoard.build/Objects-normal/arm64/WingBoard_dependency_info.dat -o /Users/bryanmarks/Library/Developer/Xcode/DerivedData/WingBoard-axmkrybtgaqwjxawruafszfdcwrq/Build/Intermediates.noindex/WingBoard.build/Debug-iphoneos/WingBoard.build/Objects-normal/arm64/WingBoard

duplicate symbol _OBJC_CLASS_$_AppsFlyerKeychainWrapper in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerKeychainWrapper.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerKeychainWrapper.o)
duplicate symbol _OBJC_METACLASS_$_AppsFlyerKeychainWrapper in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerKeychainWrapper.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerKeychainWrapper.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerKeychainWrapper.identifier in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerKeychainWrapper.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerKeychainWrapper.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerRequestCache.cachedRequests in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCache.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCache.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerRequestCache.cacheDirectoryPath in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCache.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCache.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerRequestCache.failedToInitialize in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCache.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCache.o)
duplicate symbol _OBJC_CLASS_$_AppsFlyerRequestCache in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCache.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCache.o)
duplicate symbol _OBJC_METACLASS_$_AppsFlyerRequestCache in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCache.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCache.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerRequestCache.isSendingCachedData in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCache.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCache.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerRequestCacheData._cacheKey in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCacheData.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCacheData.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerRequestCacheData._sdkVersion in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCacheData.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCacheData.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerRequestCacheData._postData in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCacheData.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCacheData.o)
duplicate symbol _OBJC_CLASS_$_AppsFlyerRequestCacheData in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCacheData.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCacheData.o)
duplicate symbol _OBJC_METACLASS_$_AppsFlyerRequestCacheData in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCacheData.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCacheData.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerRequestCacheData._requestURL in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerRequestCacheData.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerRequestCacheData.o)
duplicate symbol _OBJC_CLASS_$_AppsFlyerDictionary in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerDictionary.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerDictionary.o)
duplicate symbol _OBJC_METACLASS_$_AppsFlyerDictionary in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerDictionary.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerDictionary.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerDictionary._dict in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerDictionary.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerDictionary.o)
duplicate symbol _OBJC_CLASS_$_AppsFlyerUtils in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerUtils.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerUtils.o)
duplicate symbol _OBJC_METACLASS_$_AppsFlyerUtils in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerUtils.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerUtils.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._appsFlyerDevKey in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._useReceiptValidationSandbox in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._useUninstallSandbox in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _k60Days in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker.userEmails in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_CLASS_$_AppsFlyerTracker in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_METACLASS_$_AppsFlyerTracker in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker.sourceApplication in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker.keychain in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker.deeplink in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._isDebug in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._disableAppleAdSupportTracking in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._disableIAdTracking in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker.mBackgroundQueue in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._delegate in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker.emailCryptType in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker.platfromDevName in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._shouldCollectDeviceName in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._currencyCode in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _kNumberOfConversionDataRequestsTreshhold in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._deviceTrackingDisabled in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker.pushPayload in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker.advertiserId in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._customData in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._customerUserID in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
duplicate symbol _OBJC_IVAR_$_AppsFlyerTracker._appleAppID in:
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/Pods/AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerTracker.o)
    /Users/bryanmarks/BryanApps/WingBoard/WingBoard/WingBoard/libAppsFlyerLib.a(AppsFlyerTracker.o)
ld: 46 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by andr-ggn** [comment]
Based on your logs I can make a conclusion that you added our framework twice.
* via cocoapods(*/WingBoard/Pods/AppsFlyerFramework*)
* manually by coping `libAppsFlyerLib.a` into your project
I recommend removing WingBoard/WingBoard/libAppsFlyerLib.a from your working directory

**Comment by BFMarks** [comment]
Thanks!
